### ISSUE TITLE
Add Missing go.mod File

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#10]
Welcome to Hacktoberfest 2022!

We are open to PR/MR requests once again. 

Requirements -

- Please add a `go.mod` file with a version `go 1.13` and a new module name.

**Comment by shivam-bhadani** [comment]
working on it

**Comment by shivam-bhadani** [comment]
can you tell me about the go version should I add 1.18 (latest version) or 1.13 as you suggested

**Comment by stevenanthonyrevo** [comment]
@shivam-bhadani  I believe `go mod` was available starting to go 1.11 so I suggested 1.13 to start with.   

Let's bump to the stable 1.18 for now.

**Comment by shivam-bhadani** [comment]
@stevenanthonyrevo added go.mod file and made pull request

**Comment by shivam-bhadani** [comment]
@stevenanthonyrevo I made the pull request a while ago please can you review and merge it

**Comment by stevenanthonyrevo** [comment]
@shivam-bhadani Great work, I've merged your PR. Thanks!

**Comment by shivam-bhadani** [comment]
please add hacktoberfest-accepted tag to make my contribution official for hacktoberfest
