### ISSUE TITLE
Add Kubernetes Service .YAML

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#12]
Welcome to Hacktoberfest 2023! 

It's a brand new year (congrats!) and we are open to Merge Requests / Pull Requests. If you are new and looking to contribute please follow the [CODE OF CONDUCT](https://github.com/stevenanthonyrevo/RocketShipCountDown/blob/main/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/stevenanthonyrevo/RocketShipCountDown/blob/main/CONTRIBUTING.md) guides before starting. 

First issue... Adding a Kubernetes Service file to the application. We'd really like for this application to be available on Kubernetes but need some awesome "Spookytober" hacktoberfest folks to help out.

**Comment by darwinz** [comment]
I'd be happy to take this on

**Comment by stevenanthonyrevo** [comment]
Great work @darwinz! I've merged the PR.
