### ISSUE TITLE
Add Comments and Fix linting 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#16]
Looking for help with adding comments and formatting our codebase.

**Comment by stevenanthonyrevo** [comment]
PR #15 is approved.

**Comment by stevenanthonyrevo** [comment]
PR #14 is going to need a few adjustments before approval.

**Comment by Gordiancyber** [comment]
> PR #14 is going to need a few adjustments before approval.

will sure do so
