### ISSUE TITLE
Fix Bug found in WebSocketConnection Method

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#19]
The WebSocketConnection has a bug on Line 25 in the main.go file.  

`uri := url.URL{Scheme: "ws", Host: "hostname:port", Path: "/socket"}` 

Let's instead abstract the values and utilize either binding of `0.0.0.0` ip address or a method in Go to allow any host ip and port to connect to the socket. 

Our current scheme only works due to a hardcoded value for the `hostname` and `port`. 

To reproduce the bug, you should first access the socket via the loop back address `127.0.0.1` and see the panic error occur during any runtime logs.

```
runtime error: invalid memory address or nil pointer dereference
```

Objective to complete the issue is to fully eliminate the runtime error for any and all possible `hostnames` and preventing the hardcoding of `port`.

**Comment by mushahidq** [comment]
Hi @stevenanthonyrevo ,

I'm fairly new to Go but would like to contribute to this if someone else hasn't already take this up.

**Comment by stevenanthonyrevo** [comment]
Hi @mushahidq 

Happy Hacktoberfest 🎃, sure no problem! 

Go is the perfect language for learning, I'll assign to work on the issue. 

Thanks for your contribution! Let me know if you have questions 👍

**Comment by mushahidq** [comment]
Hi @stevenanthonyrevo 

I was trying this out and am a bit confused. 

I am able to get it working for the loopback address by removing the hardcoded websocket connection string from `rocket.templ.html` and dynamically forming the string from the `location` 
From what I understand the `WebSocketConnection`  is a client web socket connection which will connect to our websocket server and thus it will always require the address for its connection. Even after commenting the execution for that function and serving the web application on a different port, the websocket connection works if we derive the connection url correctly. Can you confirm if my understanding is correct on this? If so I can go ahead and open a PR to change the template file to derive the websocket url correctly.

Thank you,
Mushahid

**Comment by stevenanthonyrevo** [comment]
Great work, @mushahidq! 
 
See my latest [feedback](https://github.com/mushahidq/RocketShipCountDown/commit/b8ed71f2faa6d49ce4e802bf8539fc66287b94ba#commitcomment-147890436).

**Comment by stevenanthonyrevo** [comment]
@mushahidq I've merged your PR.
