### ISSUE TITLE
Swap Development to Production React@18 version 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#28]
React 18 is now available on the frontend of the project! Thanks to our contributors!

For performance reasons and better support overall. 

Let's make a few changes to the UMD url we are currently utilizing for react.js support. 

- swap the current cdn with cloudflare cdn js
- verify frontend react js functionality is working properly with update production version. 
- only replace these lines https://github.com/stevenanthonyrevo/RocketShipCountDown/blob/05d0995cd3bda99ed4a57f5126f32ba693b3cf39/templates/rocket.templ.html#L11 and https://github.com/stevenanthonyrevo/RocketShipCountDown/blob/05d0995cd3bda99ed4a57f5126f32ba693b3cf39/templates/rocket.templ.html#L12 with new lines which I will provide below. 

```
 <script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.3.1/umd/react.production.min.js"></script>
```
```
 <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/umd/react-dom.production.min.js"></script>
```

**Comment by stevenanthonyrevo** [comment]
Hi @MrSwapnilRahate, would you like to be assigned to this issue?

**Comment by MrSwapnilRahate** [comment]
Hi @stevenanthonyrevo,

I've updated the changes and created a pull request for the CDN update in the project.  You can review it https://github.com/stevenanthonyrevo/RocketShipCountDown/pull/29

If you have any new task, feel free to let me know!

**Comment by stevenanthonyrevo** [comment]
Hi @MrSwapnilRahate,

Thanks for the PR. I'll review and merge.
