### ISSUE TITLE
Build new HTML, CSS and Layout on Rocket Template

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#6]
Build a basic splash page for the countdown. 

Make sure to include the logo somewhere on the top of the page. This is an open issue, for any designers or developers to collaborate on, looking for great design work! 

It should feature a Numbered in the format of (day, hour, minute, second) Text Large in the center of the splash page. Only focus on HTML, CSS, and Layout choices.  

Freely work within the `rocket.templ.html` file.

happy hacktoberfest! 👻

**Comment by Rupesh-2003** [comment]
Hello @stevenanthonyrevo , the requirements are just a logo on top of the page and static Numbered text in the center of the page?

**Comment by stevenanthonyrevo** [comment]
Yes, @Rupesh-2003 those requirements are correct. 

Be sure to use one of the logos from the static [IMG](https://github.com/stevenanthonyrevo/RocketShipCountDown/tree/main/static/img) folder.

I am excited to see the new page you build in a Pull Request.

**Comment by stevenanthonyrevo** [comment]
Welcome to Hacktoberfest 2024! 

We'd like to revisit and reopen the issue to give new Contributors more options. Our primary goals for 2024 is to give our home page a full redesign it desperately deserves.  

We have a few issues already available and will continue to open new issues based on feedback and general enagement. 

The first issues we have opened are:
#17 
#18 

Once those have been closed we can officially close this issue. If you have suggestions or questions please apply them to the correct issue numbers. I'll be opening additional issues when needed or required. So feel free to be on the look out for more opportunities to contribute. 

With that said, Welcome and we can not wait for your contributions. 💀
