### ISSUE TITLE
Add CSS to Homepage

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#7]
Welcome to Hacktoberfest 2022! 

We are open to PR/MR requests once again. If you are new and would like to contribute we ask for an updated HOMEPAGE to be added to the project. 

Requirements - 

- Add CSS Stylesheets 
- Build a countdown to the Homepage with mobile responsiveness enabled

**Comment by Pranav4399** [comment]
I can work on this.

**Comment by shivam-bhadani** [comment]
I want to work on this

**Comment by stevenanthonyrevo** [comment]
Happy Hacktoberfest @Pranav4399 and @shivam-bhadani! 

We have plenty of new issues in the backlog so feel free to get started, and submit a PR!

**Comment by minhaj-313** [comment]
Hi, I want to Contribute in Your project can you Please Assign my Hacktoberfest PR

**Comment by stevenanthonyrevo** [comment]
Happy Hacktoberfest @minhaj-313! 

Thanks for your interest in the project, please submit a PR! 

We only accept valid contributions please be sure to read over our [README.md ](https://github.com/stevenanthonyrevo/RocketShipCountDown/blob/main/README.md) and [Contributing Documentation](https://github.com/stevenanthonyrevo/RocketShipCountDown/blob/main/CONTRIBUTING.md)
