### ISSUE TITLE
Add Navigation Bar to Homepage

### ISSUE THREAD

**Issue by stevenanthonyrevo** [stevenanthonyrevo/RocketShipCountDown#9]
Welcome to Hacktoberfest 2022!

We are open to PR/MR requests once again. If you are new and would like to contribute we ask for an updated HOMEPAGE to be added to the project.

Requirements -

- Add Twitter Bootstrap 5 Navigation 
- Create multiple pages named FAQ, About Us, and Home (acceptable to be blank pages, functionality needs to work)

**Comment by shivam-bhadani** [comment]
Ok I will do it please assign me this issue

**Comment by Sarabjeet108** [comment]
Would like to work on this issue. please assign it to me.

**Comment by shivam-bhadani** [comment]
@stevenanthonyrevo I am not able to locate go.mod file in your repository please let me know about this

**Comment by stevenanthonyrevo** [comment]
I'll open an issue about the missing `go.mod` file and I'll get that added in. 

@shivam-bhadani is this something you would be willing to contribute?

**Comment by shivam-bhadani** [comment]
> I'll open an issue about the missing `go.mod` file and I'll get that added in.
> 
> @shivam-bhadani is this something you would be willing to contribute?

Yes I can add go.mod file assign me this issue so that I can start working on it

**Comment by stevenanthonyrevo** [comment]
@shivam-bhadani I've assigned you! Thanks for your contribution!

**Comment by stevenanthonyrevo** [comment]
@Sarabjeet108 I've assigned you to the issue here! Thanks for your contribution!
